name: Update and Convert IPTV Sources

on:
  schedule:
    - cron: '0 3 * * *'
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Fetch latest IPTV sources
        run: |
          echo "Fetching the latest IPTV sources..."
          mkdir -p data
          curl -o data/iptv.m3u https://iptv-org.github.io/iptv/index.m3u

      - name: Debug IPTV file
        run: |
          echo "Checking IPTV source file..."
          if [ ! -s data/iptv.m3u ]; then
            echo "Error: IPTV file is empty or missing!"
            exit 1
          fi
          head -n 20 data/iptv.m3u

      - name: Create group_config.txt
        run: |
          echo "Creating group_config.txt..."
          cat <<EOF > group_config.txt
          首选直播源,首选|主推
          IPV6央卫数字,IPV6|中央|数字
          IPV4地方频道,IPV4|地方
          直播中国,中国|直播
          代理源(180),代理|180
          AKTV(61),AKTV|61
          四季TV(62),四季TV|62
          HLS-TV(18),HLS|18
          JDSP源(23),JDSP|23
          测试直播源,测试|实验
          动作片1224,动作片|1224
          科幻片1224,科幻|1224
          恐怖片1224,恐怖片|1224
          战争片1224,战争片|1224
          台湾地区FM,台湾|FM
          大陆地区FM,大陆|FM
          国家级FM,国家级|FM
          EOF
          cat group_config.txt

      - name: Create groups and filter channels
        run: |
          echo "Creating groups and filtering channels..."
          mkdir -p data/groups
          while IFS= read -r group; do
            group_name=$(echo "$group" | cut -d ',' -f1)
            keywords=$(echo "$group" | cut -d ',' -f2)

            echo "Processing group: $group_name with keywords: $keywords"
            mkdir -p "data/groups/$group_name"

            # 筛选并处理未匹配情况
            grep -E "($keywords)" -A1 data/iptv.m3u > "data/groups/$group_name/${group_name}.m3u" || echo "No matches found for $group_name" > "data/groups/$group_name/${group_name}.m3u"
          done < group_config.txt

      - name: Collect and output filtered channels
        run: |
          echo "Collecting and outputting filtered channels to final output..."
          mkdir -p output
          > output/final_output.m3u  # 清空最终输出文件

          for group_dir in data/groups/*; do
            group_name=$(basename "$group_dir")
            echo "Processing group: $group_name"
            
            # 为每个组读取相关 m3u 文件并处理
            if [ -f "$group_dir/${group_name}.m3u" ]; then
              while IFS= read -r line; do
                if [[ "$line" =~ .*(m3u8|ts|mp4).*(http|https).*$ ]]; then
                  # 模糊匹配到直播源并追加到最终输出文件
                  echo "$group_name,#genre#" >> output/final_output.m3u
                  echo "$line" >> output/final_output.m3u
                fi
              done < "$group_dir/${group_name}.m3u"
            else
              echo "No IPTV source found for $group_name"
            fi
          done

      - name: Upload the final output file
        uses: actions/upload-artifact@v3
        with:
          name: final-iptv-output
          path: output/final_output.m3u
