name: Update and Convert IPTV Sources

on:
  schedule:
    # 每天凌晨 3 点运行
    - cron: '0 3 * * *'
  workflow_dispatch: # 手动触发工作流

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      # 检查出仓库代码
      - name: Checkout repository
        uses: actions/checkout@v3

      # 拉取最新直播源
      - name: Fetch latest IPTV sources
        run: |
          mkdir -p data
          curl -o data/iptv.m3u https://iptv-org.github.io/iptv/index.m3u

      # 筛选特定分组（香港、台湾）和直播源（HBO、Hub）
      - name: Filter specific groups and keywords
        run: |
          echo "Filtering Hong Kong, Taiwan, HBO, and Hub channels..."
          mkdir -p data/groups
          
          # 筛选香港和台湾的频道分组
          grep -E "(香港|Taiwan|台灣)" -A1 data/iptv.m3u > data/groups/hk_tw.m3u
          
          # 筛选 HBO 和 Hub 直播源
          grep -E "(HBO|Hub)" -A1 data/iptv.m3u > data/groups/hbo_hub.m3u

          # 合并筛选后的频道到总文件
          cat data/groups/*.m3u > data/filtered_iptv.m3u

      # 验证直播源链接
      - name: Validate and filter working links
        run: |
          echo "Validating live stream links for availability..."
          mkdir -p data/valid
          > data/valid/working_links.txt
          > data/valid/invalid_links.txt

          # 禁用退出状态码错误中断
          set +e
          awk '/http/{print $0}' data/filtered_iptv.m3u | while read -r link; do
            status=$(curl -s -o /dev/null -w "%{http_code}" --max-time 3 "$link" || true)
            if [ "$status" -eq 200 ]; then
              echo "$link" >> data/valid/working_links.txt
            else
              echo "$link" >> data/valid/invalid_links.txt
            fi
          done

          # 恢复默认错误中断行为
          set -e

      # 转换 M3U 到 TXT 格式
      - name: Convert M3U to TXT
        run: |
          echo "Converting M3U to TXT format..."
          mkdir -p data/valid/groups/txt

          # 转换每个分组文件
          for group in hk_tw hbo_hub; do
            input_file="data/groups/$group.m3u"
            output_file="data/valid/groups/txt/$group.txt"
            echo "$group,#genre#" > "$output_file"

            # 解析 M3U 并生成 TXT 格式
            awk '/^#EXTINF/ { name=gensub(/.*,(.*)$/, "\\1", "g", $0); next } /http/ { print name "," $0 }' "$input_file" >> "$output_file"
          done

          # 合并所有 TXT 文件
          cat data/valid/groups/txt/*.txt > data/valid/valid_iptv.txt

      # 提交更新到仓库
      - name: Commit and push updates
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add .
          git commit -m "Updated and converted IPTV sources to TXT format [skip ci]"
          git push
